Carea/Models/Terms_Conditions.cs
namespace Carea.Entities
{
    public class Terms_Conditions
    {
        public int Id { get; set; }
        public string Details { get; set; }

    }
}

Carea/Controllers/TermsConditionsController.cs
using Carea.Entities;
using Carea.Interfaces;
using Carea.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Carea.Controllers
{
    [Authorize(Roles = "Admin")]

    public class TermsConditionsController : Controller
    {
        private readonly ITerms_ConditionsSevice _doc;

        private readonly IMapper mapper;

        public TermsConditionsController(IMapper mapper, ITerms_ConditionsSevice doc)
        {
            this.mapper = mapper;
            this._doc = doc;
        }

        public IActionResult Index()
        {
            var data = _doc.Get();
            var result = mapper.Map<IEnumerable<Terms_ConditionsVM>>(data);
            return View(result);

        }

        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]

        public  IActionResult Create(Terms_ConditionsVM obj)
        {
            try
            {
                var data = mapper.Map<Terms_Conditions>(obj);
                _doc.Create(data);
                return RedirectToAction("Index");
            }
            catch (Exception )
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var data = _doc.GetById(id);
            var result = mapper.Map<Terms_ConditionsVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Delete(Terms_ConditionsVM model)
        {
            var olddata = _doc.GetById(model.Id);
            _doc.Delete(olddata);
            return RedirectToAction("Index");
        }



        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _doc.GetById(id);
            var result = mapper.Map<Terms_ConditionsVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(Terms_ConditionsVM model)

        {
            var data = mapper.Map<Terms_Conditions>(model);
            _doc.Edit(data);
            return RedirectToAction("Index");
        }

    }

}

Carea/Views/TermsConditions/Create.cshtml
@model Terms_ConditionsVM;
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center>
    <h1>
        Create Terms and Conditions
</h1>
</center>

<!-- // Basic multiple Column Form section start -->
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Details</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form class="form" asp-action="Create" asp-controller="TermsConditions">
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-12 col-12">
                                        <div class="form-label-group">
                                            <input asp-for="Details" type="text" id="first-name-column" class="form-control" placeholder="Details">
                                            <label asp-for="Details">Details</label>
                                        </div>
                                    </div>



                                    <div class="col-12">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1">Submit</button>
                                        <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- // Basic Floating Label Form section end -->

Carea/Views/TermsConditions/Delete.cshtml
@model Terms_ConditionsVM;
@{
	ViewData["Title"] = "Delete";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<center>
	<h1>
		Delete Terms and Conditions
</h1>
</center>

<!-- // Basic multiple Column Form section start -->
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Details</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form class="form" asp-action="Delete" asp-controller="TermsConditions">
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-12 col-12">

                                        <div class="form-label-group">
                                            <input asp-for="Id" type="text" id="first-name-column" class="form-control" placeholder="Id">
                                            <label asp-for="Id">Id</label>
                                        </div>
                                        <div class="form-label-group">
                                            <input asp-for="Details" type="text" id="first-name-column" class="form-control" placeholder="Details" name="fname-column" readonly>
                                            <label asp-for="Details">Details</label>
                                        </div>
                                    </div>



                                    <div class="col-12">
                                        <button type="submit" class="btn btn-danger mr-1 mb-1">Delete</button>
                                        <a asp-action="Index" asp-controller="TermsConditions" type="submit" class="btn btn-outline-danger mr-1 mb-1">Back to Index</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- // Basic Floating Label Form section end -->

Carea/Views/TermsConditions/Edit.cshtml
@model Terms_ConditionsVM;
@{
	ViewData["Title"] = "Edit";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<center>
	<h1>
		Edit Terms and Conditions
	</h1>
</center>

<!-- // Basic multiple Column Form section start -->
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Details</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form class="form" asp-action="Edit" asp-controller="TermsConditions">
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-12 col-12">

                                        <div class="form-label-group">
                                            <input asp-for="Details" type="text" id="first-name-column" class="form-control" placeholder="Details">
                                            <label asp-for="Details">Details</label>
                                        </div>
                                    </div>



                                    <div class="col-12">
                                        <button type="submit" class="btn btn-success mr-1 mb-1">Edit</button>
                                        <a asp-action="Index" asp-controller="TermsConditions" type="submit" class="btn btn-outline-success mr-1 mb-1">Back to Index</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- // Basic Floating Label Form section 

Carea/Views/TermsConditions/Index.cshtml
@model IEnumerable<Terms_ConditionsVM>;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center>
    <h1>
        All Terms and Conditions
    </h1>
       
</center>
<!-- Scroll - horizontal and vertical table -->
<section id="horizontal-vertical">
   
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="dt-buttons btn-group">
                        <a asp-action="Create" asp-controller="TermsConditions" class="btn btn-outline-primary" style="margin:20px">
                            <span><i class="feather icon-plus"></i></span>
                        </a>
                    </div>
                </div>
                <div class="card-content">
                    <div class="card-body card-dashboard">
                        <div class="table-responsive">
                            <table class="table nowrap scroll-horizontal-vertical">
                                <thead>
                                    <tr>
                                        <th>Details</th>
                                        <th>Edit</th>
                                        <th>Delete</th>


                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model) {
                                        <tr>
                                            <td>@item.Details</td>
                                            <td class="product-action">
                                                <a asp-action="Edit" asp-controller="TermsConditions" class="btn btn-success" asp-route-id="@item.Id">
                                                    <span class="action-edit"><i class="feather icon-edit">Edit</i></span>
                                                </a>
                                            </td>
                                            <td class="product-action">
                                                <a asp-action="Delete" asp-controller="TermsConditions" class="btn btn-danger" asp-route-id="@item.Id">
                                                    <span class="action-delete"><i class="feather icon-trash ">Delete</i></span>
                                                </a>
                                            </td>

                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ Scroll - horizontal and vertical table -->