Carea/Models/Offers.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Carea.Models 
{
	public class Offers
	{
        public int Id { get; set; }
        public int Discount { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
		public int CarId { get; set; }		
		[ForeignKey("CarId")]
		public Cars? Cars { get; set; }
	}
}

Carea/Controllers/OffersController.cs
using AutoMapper;
using Carea.BLL.Interface;
using Carea.Models;
using Carea.ViewModels;
using Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Carea.Controllers
	{
    [Authorize(Roles = "Admin")]

    public class OffersController : Controller
		{
		private readonly IOffersRep _Ident;
		private readonly IMapper mapper;

		public OffersController(IMapper mapper, IOffersRep ident) {
			this.mapper = mapper;
			this._Ident = ident;
		}

		public IActionResult Index() {
			var data = _Ident.Get();
			var result = mapper.Map<IEnumerable<OffersVM>>(data);
			return View(result);

		}



		[HttpGet]

		public IActionResult Create() {
			return View();
		}
		[HttpPost]

		public async Task<IActionResult> Create(OffersVM obj)
		{
			try {
				var data = mapper.Map<Offers>(obj);
				_Ident.Creat(data);
				return RedirectToAction("Index");
			}
			catch (Exception ex) {
				return View();
			}
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var data = _Ident.GetById(id);
			var result = mapper.Map<OffersVM>(data);
			return View(result);
		}
		[HttpPost]
		public IActionResult Delete(OffersVM model)
		{
			var olddata = _Ident.GetById(model.Id);
			_Ident.Delete(olddata);
			return RedirectToAction("Index");
		}



		[HttpGet]
		public IActionResult Edit(int id)
		{
			var data = _Ident.GetById(id);
			var result = mapper.Map<OffersVM>(data);
			return View(result);
		}
		[HttpPost]

		public IActionResult Edit(OffersVM model)
		{
				var data = mapper.Map<Offers>(model);
				_Ident.Edit(data);
				return RedirectToAction("Index");
			
			

		}
		public IActionResult Details(int id) {
			var data = _Ident.GetById(id);
			var result = mapper.Map<OffersVM>(data);
			return View(result);
		}
	}
}

Carea/Views/Offers/Create.cshtml
@model OffersVM

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
	<h1>Create New Offer</h1>
</Center>
<form asp-action="Create" asp-controller="Offers" enctype="multipart/form-data">
	<div class="form-group">
		<label for="Name">Offer Discount</label>
		<input class="form-control" type="text" placeholder="Add Offer Discount Here .. " asp-for="Discount">
		<br />

	</div>
	<div class="form-group">
		<label for="Name">Offer Description</label>
		<input class="form-control" type="text" placeholder="Add Offer Description .. " asp-for="Description">
		<br />

	</div>

	<div class="form-group">
		<label for="Name">Car Id</label>
		<input class="form-control" type="text" placeholder="Add CarId  .. " asp-for="CarId">
		<br />

	</div><div class="form-group">
		<label for="Name">Title</label>
		<input class="form-control" type="text" placeholder="Title .. " asp-for="Title">
		<br />

	</div>
	@*<div class="form-group">
		<label for="Photo">Choose Photo</label>
		<input type="file" class="form-control-file form-control height-auto" asp-for="Cars.Car_Photo_Color">
	</div>*@
	<div class="col-12">
		<button type="submit" class="btn btn-lg btn-primary">Save</button>
		<button type="reset" class="btn btn-danger btn-lg">Cancel</button>
	</div>


</form>

Carea/Views/Offers/Delete.cshtml
@model OffersVM

@{
	ViewData["Title"] = "Delete";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
	<h1>Delete Offer</h1>
</Center>

<form asp-action="Delete" asp-controller="Offers" enctype="multipart/form-data">
@*	<center>
		<img src="~/Uploads/Brand/@Model.LogoUrl" class="mb-3" width="300" height="200" />

	</center>*@
	<br />
	<div class="form-group">
		<label for="Name">Discount</label>
		<input class="form-control" type="text" asp-for="Discount" readonly>
		<br />

	</div>
	<div class="form-group">
		<label for="Name">Description</label>
		<input class="form-control" type="text" asp-for="Description" readonly>
		<br />

	</div>

	<div class="col-12">
		<button type="submit" class="btn btn-lg btn-primary">Save</button>
		<a asp-action="Index" asp-controller="Offers" class="btn btn-danger btn-lg">Cancel</a>
	</div>


</form>

Carea/Views/Offers/Details.cshtml
@model OffersVM

@{
	ViewData["Title"] = "Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
	<h1>Details Of Offer</h1>
</Center>

<form asp-action="Details" asp-controller="Offers" enctype="multipart/form-data">

	<br />
	<div class="form-group">
		<label for="Name">Discount</label>
		<input class="form-control" type="text" asp-for="Discount" readonly>
	</div>
	<br />

	<div class="form-group">
		<label for="Name">Description</label>
		<input class="form-control" type="text" asp-for="Description" readonly>

	</div>
	<br />
	<div class="form-group">
		<label for="Name">Title</label>
		<input class="form-control" type="text" asp-for="Title" readonly>

	</div>
	<br />
	
		<br />
		<div class="form-group">
			<label for="Name">Car Name</label>
			<input class="form-control" type="text" asp-for="Cars.Car_Name" readonly>
	</div>
			<br />
			<div class="form-group">
				<label for="Name">Car Price</label>
				<input class="form-control" type="text" asp-for="Cars.Car_Price" readonly>
				<br />
	</div>



	<div class="col-12">
		<a asp-controller="Offers" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary mr-1"><i class="feather icon-edit-1"></i> Edit</a>
		<button asp-controller="Offers" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger"><i class="feather icon-trash-2"></i> Delete</button>
	</div>


</form>

Carea/Views/Offers/Edit.cshtml
@model OffersVM

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
    <h1>Edit Offer</h1>
</Center>


<form asp-action="Edit" asp-controller="Offers" enctype="multipart/form-data">
	<div class="form-group">
		<label for="Name">Offer Discount</label>
		<input class="form-control" type="text" placeholder="Add Offer Discount Here .. " asp-for="Discount">
		<br />

	</div>
	<div class="form-group">
		<label for="Name">Offer Description</label>
		<input class="form-control" type="text" placeholder="Add Offer Description .. " asp-for="Description">
		<br />

	</div>

	<div class="form-group">
		<label for="Name">Car Id</label>
		<input class="form-control" type="text" placeholder="Add CarId  .. " asp-for="CarId">
		<br />
	</div>

	</div><div class="form-group">
		<label for="Name">Title</label>
		<input class="form-control" type="text" placeholder="Title .. " asp-for="Title">
		<br />

	</div>
	@*<div class="form-group">
	<label for="Photo">Choose Photo</label>
	<input type="file" class="form-control-file form-control height-auto" asp-for="Cars.Car_Photo_Color">
	</div>*@
	<div class="col-12">
		<button type="submit" class="btn btn-lg btn-primary">Save</button>
		<button type="reset" class="btn btn-danger btn-lg">Cancel</button>
	</div>
</form>

Carea/Views/Offers/Index.cshtml
@model IEnumerable<OffersVM>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center>
    <h1>Index Of Offers</h1>
</center>


<section id="basic-datatable">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="dt-buttons btn-group">
                        <a asp-action="Create" asp-controller="Offers" class="btn btn-outline-primary" style="margin:20px">
                            <span><i class="feather icon-plus"></i></span>
                        </a>
                    </div>
                </div>
             
                <div class="card-content">
                    <div class="card-body card-dashboard">
                        @*                        <p class="card-text">DataTables has most features enabled by default, so all you need to do to use it with your own ables is to call the construction function: $().DataTable();.</p>
                        *@                        <div class="table-responsive">
                            <table class="table zero-configuration">
                                <thead>
                                    <tr>
                                        <th>Discount</th>
                                        <th>Description</th>
                                        <th>CarId</th>
                                        <th>Details</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model) {
                                        <tr>
                                            <td>@item.Discount</td>
                                            <td>@item.Description</td>
                                            <td>@item.CarId</td>
                                            <td><a asp-controller="Offers" asp-action="Details" asp-route-id="@item.Id" class="btn btn-success">Details</a></td>
                                            <td><a asp-controller="Offers" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Update</a></td>
                                            <td><a asp-controller="Offers" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></td>
                                        </tr>
                                    }
                                <tfoot>
                                    <tr>
                                        <th>Discount</th>
                                        <th>Description</th>
                                        <th>CarId</th>
                                        <th>Details</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>