Carea/Controllers/PhotoColorController.cs
using AutoMapper;
using Carea.BLL.Interface;
using Carea.Models;
using Carea.ViewModels;
using Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Carea.Controllers
{
    [Authorize(Roles = "Admin")]

    public class PhotoColorController : Controller
    {
        private readonly ICar_Photo_ColorRep _Ident;
        private readonly ICarsRep _car;
        private readonly IMapper mapper;

        public PhotoColorController(IMapper mapper, ICar_Photo_ColorRep ident, ICarsRep car)
        {
            this.mapper = mapper;
            this._Ident = ident;
            _car = car;
        }

        public IActionResult Index()
        {
            var data = _Ident.Get();
            var result = mapper.Map<IEnumerable<Car_Photo_ColorVM>>(data);
            return View(result);

        }



        [HttpGet]

        public IActionResult Create(int id)
        {
            var car = _car.GetById(id);
            var result = mapper.Map<CarsVM>(car);
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create(Car_Photo_ColorVM obj,int id)
        {
            //try
            //{
                var img = UploadCv.uploadFile("Uploads/Cars", obj.Photo);
                var data = mapper.Map<Car_Photo_Color>(obj);
                data.imgUrl = img;
                data.Car_Id = id;
            Car_Photo_Color model = new Car_Photo_Color { Car_Id = id, imgUrl = img ,Color_Code=obj.Color_Code};

            _Ident.Creat(model);
                return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var data = _Ident.GetById(id);
            var result = mapper.Map<Car_Photo_ColorVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Delete(Car_Photo_ColorVM model)
        {
            UploadCv.RemoveFile("Uploads/Cars", model.imgUrl);
            var olddata = _Ident.GetById(model.Id);
            _Ident.Delete(olddata);
            return RedirectToAction("Index","Cars");
        }



        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _Ident.GetById(id);
            var result = mapper.Map<Car_Photo_ColorVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(Car_Photo_ColorVM model)

        {
            if (model.Photo == null)
            {
                var url = model.imgUrl;
                var data = mapper.Map<Car_Photo_Color>(model);
                data.imgUrl = url;
                _Ident.Edit(data);
                return RedirectToAction("Index", "Cars");
            }
            else
            {
                var IdentityImgUrl = UploadCv.uploadFile("Uploads/Cars", model.Photo);
                var data = mapper.Map<Car_Photo_Color>(model);
                data.imgUrl = IdentityImgUrl;
                _Ident.Edit(data);
                return RedirectToAction("Index", "Cars");
            }

        }
        public IActionResult Details(int id)
        {
            var data = _Ident.GetById(id);
            var result = mapper.Map<Car_Photo_ColorVM>(data);
            return View(result);
        }

    }

}

Carea/Views/PhotoColor/Create.cshtml
@model Car_Photo_ColorVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

				<Center>
					<h1>Create New Photo For Car</h1>
				</Center>

			<form asp-action="Create" asp-controller="PhotoColor" enctype="multipart/form-data">
				
		<div class="form-group">
										<label for="Name">Color Code</label>
										<input class="form-control" type="text" placeholder="Add Color Code " asp-for="Color_Code">
										<br />

									</div>	
							<div class="form-group">
								<label for="Photo">Choose Photo</label>
								<input type="file" class="form-control-file form-control height-auto" asp-for="Photo">
							</div>
							<div class="col-12">
								<button type="submit" class="btn btn-lg btn-primary">Save</button>
								<button type="reset" class="btn btn-danger btn-lg">Cancel</button>
							</div>

				
			</form>

Carea/Views/PhotoColor/Delete.cshtml
@model Car_Photo_ColorVM

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>



<form asp-action="Delete" asp-controller="PhotoColor" enctype="multipart/form-data">
	<center>
		<img src="~/Uploads/Cars/" class="mb-3" width="300" height="200" />

	</center>
	<br />
	<div class="form-group">
		<label for="Name">Color Code</label>
		<input class="form-control" type="text" asp-for="Color_Code" readonly>
		<br />

	</div>


	<div class="col-12">
		<button type="submit" class="btn btn-lg btn-primary">Save</button>
		<a asp-action="Index" asp-controller="PhotoColor" class="btn btn-danger btn-lg">Cancel</a>
	</div>


</form>

Carea/Views/PhotoColor/Details.cshtml
@model Car_Photo_ColorVM

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
    <h1>Details</h1>
</Center>


<form asp-action="Details" asp-controller="PhotoColor" enctype="multipart/form-data">
	<center>
		<img src="~/Uploads/Cars/@Model.imgUrl" class="mb-3" width="300" height="200" />

	</center>
	<br />
						<div class="form-group">
		<label for="Name">Color Code</label>
							<input class="form-control" type="text"  asp-for="Color_Code"readonly>
							<br />

						</div>
						<div class="form-group">
						<label for="Name">Car Name : @Model.Cars.Car_Name</label>
							<br />

						</div>


	<div class="col-12">
		<a asp-controller="PhotoColor" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary mr-1"><i class="feather icon-edit-1"></i> Edit</a>
		<button asp-controller="PhotoColor" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger"><i class="feather icon-trash-2"></i> Delete</button>
	</div>

				
</form>

Carea/Views/PhotoColor/Edit.cshtml
@model Car_Photo_ColorVM

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>
<form asp-action="Edit" asp-controller="PhotoColor" enctype="multipart/form-data">
	<input  type="hidden" asp-for="@Model.Id"/>
	<input  type="hidden" asp-for="@Model.imgUrl"/>
	<input  type="hidden" asp-for="@Model.Car_Id"/>
	<center>
		<img src="~/Uploads/Cars/@Model.imgUrl" class="mb-3" width="300" height="200" />

	</center>
	<br />
	<div class="form-group">
		<label for="Name">Color Code</label>
		<input class="form-control" type="text" asp-for="Color_Code" >
		<br />

	</div>
	<div class="form-group">
		<label for="Photo">Choose Photo</label>
		<input type="file" class="form-control-file form-control height-auto" asp-for="Photo">
	</div>

	<div class="col-12">
		<button type="submit" class="btn btn-lg btn-primary">Save</button>
		<a asp-action="Index" asp-controller="PhotoColor" class="btn btn-danger btn-lg">Cancel</a>
	</div>


</form>

Carea/Views/PhotoColor/Index.cshtml
@model IEnumerable<Car_Photo_ColorVM>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<section id="basic-datatable">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="dt-buttons btn-group">
                        <a asp-action="Create" asp-controller="Brands" class="btn btn-outline-primary" style="margin:20px">
                            <span><i class="feather icon-plus"></i></span>
                        </a>
                    </div>
                </div>

                <div class="card-content">
                    <div class="card-body card-dashboard">
@*                        <p class="card-text">DataTables has most features enabled by default, so all you need to do to use it with your own ables is to call the construction function: $().DataTable();.</p>
*@                        <div class="table-responsive">
                            <table class="table zero-configuration">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Color Code</th>
                                        <th>Details</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Color_Code</td>
                                            <td><a asp-controller="PhotoColor" asp-action="Details" asp-route-id="@item.Id" class="btn btn-success">Details</a></td>
                                            <td><a asp-controller="PhotoColor" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Update</a></td>
                                            <td><a asp-controller="PhotoColor" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></td>
                                        </tr>
                                    }
                                <tfoot>
                                    <tr>
                                        <th>Id</th>
                                        <th>Color Code</th>
                                        <th>Details</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>