Carea/Models/Brand.cs
namespace Carea.Models
{
    public class Brand
    {
        public int Id { get; set; }
        public string BrandName { get; set; }
        public string LogoUrl { get; set; }
        public string Phone { get; set; }
        public ICollection<Cars> Cars { get; set; }
    }
}

Carea/Controllers/BrandController.cs
using AutoMapper;
using Carea.BLL.Interface;
using Carea.Models;
using Carea.ViewModels;
using Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
namespace Carea.Controllers
{
    [Authorize(Roles = "Admin")]

    public class BrandController : Controller
    {
        private readonly IBrandRep _Ident;
        private readonly IMapper mapper;

        public BrandController(IMapper mapper, IBrandRep ident)
        {
            this.mapper = mapper;
            this._Ident = ident;
        }

        public IActionResult Index()
        {
            var data = _Ident.Get();
            var result = mapper.Map<IEnumerable<BrandVM>>(data);
            return View(result);

        }



        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create(BrandVM obj)
        {
            try
            {
                var img = UploadCv.uploadFile("Uploads/Brand", obj.Photo);
                var data = mapper.Map<Brand>(obj);
                data.LogoUrl = img;
                _Ident.Creat(data);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var data = _Ident.GetById(id);
            var result = mapper.Map<BrandVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Delete(BrandVM model)
        {
            UploadCv.RemoveFile("Uploads/Brand", model.LogoUrl);
            var olddata = _Ident.GetById(model.Id);
            _Ident.Delete(olddata);
            return RedirectToAction("Index");
        }



        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _Ident.GetById(id);
            var result = mapper.Map<BrandVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(BrandVM model)

        {
            if (model.Photo == null)
            {
                var url = model.LogoUrl;
                var data = mapper.Map<Brand>(model);
                data.LogoUrl = url;
                _Ident.Edit(data);
                return RedirectToAction("Index");
            }
            else
            {
                var IdentityImgUrl = UploadCv.uploadFile("Uploads/Brand", model.Photo);
                var data = mapper.Map<Brand>(model);
                data.LogoUrl = IdentityImgUrl;
                _Ident.Edit(data);
                return RedirectToAction("Index");
            }

        }
        public IActionResult Details(int id)
        {
            var data = _Ident.GetById(id);
            var result = mapper.Map<BrandVM>(data);
            return View(result);
        }

    }

}

Carea/Views/Brand/Create.cshtml
@model BrandVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
	<h1>Create New Brand</h1>
</Center>

<form asp-action="Create" asp-controller="Brand" enctype="multipart/form-data">
						<div class="form-group">
							<label for="Name">Brand Name</label>
							<input class="form-control" type="text" placeholder="Add Brand Name Here .. " asp-for="BrandName">
							<br />

						</div>
						<div class="form-group">
		<label for="Name">Phone</label>
		<input class="form-control" type="text" placeholder="Add Phone Here .. " asp-for="Phone">
							<br />

						</div>
	<div class="form-group">
		<label for="Photo">Choose Photo</label>
		<input type="file" class="form-control-file form-control height-auto" asp-for="Photo">
	</div>
	<div class="col-12">
		<button type="submit" class="btn btn-lg btn-primary">Save</button>
		<button type="reset" class="btn btn-danger btn-lg">Cancel</button>
	</div>

				
</form>

Carea/Views/Brand/Delete.cshtml
@model BrandVM

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
    <h1>Delete Brand</h1>
</Center>

<form asp-action="Delete" asp-controller="Brand" enctype="multipart/form-data">
	<center>
		<img src="~/Uploads/Brand/@Model.LogoUrl" class="mb-3" width="300" height="200" />

	</center>
	<br />
						<div class="form-group">
							<label for="Name">Brand Name</label>
							<input class="form-control" type="text"  asp-for="BrandName"readonly>
							<br />

						</div>
						<div class="form-group">
		<label for="Name">Phone</label>
		<input class="form-control" type="text" asp-for="Phone" readonly>
							<br />

						</div>

	<div class="col-12">
		<button type="submit" class="btn btn-lg btn-primary">Save</button>
		<a asp-action="Index" asp-controller="Brand" class="btn btn-danger btn-lg">Cancel</a>
	</div>

				
</form>

Carea/Views/Brand/Details.cshtml
@model BrandVM

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
    <h1>Details Of Brand</h1>
</Center>

<form asp-action="Details" asp-controller="Brand" enctype="multipart/form-data">
	<center>
		<img src="~/Uploads/Brand/@Model.LogoUrl" class="mb-3" width="300" height="200" />

	</center>
	<br />
						<div class="form-group">
							<label for="Name">Brand Name</label>
							<input class="form-control" type="text"  asp-for="BrandName"readonly>
							<br />

						</div>
						<div class="form-group">
		<label for="Name">Phone</label>
		<input class="form-control" type="text" asp-for="Phone" readonly>
							<br />

						</div>

	<div class="col-12">
		<a asp-controller="Brand" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary mr-1"><i class="feather icon-edit-1"></i> Edit</a>
		<button asp-controller="Brand" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger"><i class="feather icon-trash-2"></i> Delete</button>
	</div>

				
</form>

Carea/Views/Brand/Edit.cshtml
@model BrandVM

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<Center>
    <h1>Edit Brand</h1>
</Center>

<form asp-action="Edit" asp-controller="Brand" enctype="multipart/form-data">
	<center>
		<img src="~/Uploads/Brand/@Model.LogoUrl" class="mb-3" width="300" height="200" />

	</center>
	<br />
						<div class="form-group">
							<label for="Name">Brand Name</label>
							<input class="form-control" type="text"  asp-for="BrandName">
							<br />

						</div>
						<div class="form-group">
		<label for="Name">Phone</label>
		<input class="form-control" type="text"  asp-for="Phone">
							<br />

						</div>

	<div class="form-group">
		<label for="Photo">Choose Photo</label>
		<input type="file" class="form-control-file form-control height-auto" asp-for="Photo">
	</div>

	<div class="col-12">
		<input type="submit" value="Save Changes" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1" />
		<a asp-action="Delete" asp-controller="Brand" class="btn btn-danger btn-lg">Delete</a>
	</div>

				
</form>

Carea/Views/Brand/Index.cshtml
@model IEnumerable<BrandVM>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center>
    <h1>Index Of Brands</h1>
</center>


<section id="basic-datatable">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="dt-buttons btn-group" style="width:50px">
                        <a asp-action="Create" asp-controller="Brand" class="btn btn-outline-primary" style="margin:20px">
                            <span><i class="feather icon-plus"></i></span>
                        </a>
                    </div>
                </div>
                
                <div class="card-content">
                    <div class="card-body card-dashboard">
@*                        <p class="card-text">DataTables has most features enabled by default, so all you need to do to use it with your own ables is to call the construction function: $().DataTable();.</p>
*@                        <div class="table-responsive">
                            <table class="table zero-configuration">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Brand Name</th>
                                        <th>Phone</th>
                                        <th>Details</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.BrandName</td>
                                            <td>@item.Phone</td>
                                            <td><a asp-controller="Brand" asp-action="Details" asp-route-id="@item.Id" class="btn btn-success">Details</a></td>
                                            <td><a asp-controller="Brand" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Update</a></td>
                                            <td><a asp-controller="Brand" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></td>
                                        </tr>
                                    }
                                <tfoot>
                                    <tr>
                                        <th>Id</th>
                                        <th>Brand Name</th>
                                        <th>Phone</th>
                                        <th>Details</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>